version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbit-mq
    ports:
      - 5672:5672
      - 15672:15672

  healthy:
    image: busybox
    restart: "no"
    container_name: health_checker
    depends_on:
      zookeeper:
        condition: service_started
      kafka:
        condition: service_started
      rabbitmq:
        condition: service_started